# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: staticAid
author: Hillel Arnold
email: hillel@hillelarnold.com
description: > # this means to ignore newlines until "baseurl:"
  A Jekyll-based static site generator for archival description in JSON.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: helrond
github_username:  helrond

# Build settings
markdown: kramdown
exclude :
  - utilities
  - node_modules
